In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Iris copy.csv')
df.drop(columns = ['Id'], inplace= True)

In [3]:
type = []
for i in df.Species:
    if i == 'Iris-setosa':
        i = 0
    elif i == 'Iris-versicolor':
        i = 1
    else:
        i = 2

    type.append(i)

In [4]:
df['type'] = type

In [5]:
df.drop(columns= ['Species'], inplace= True)

In [6]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  type
0              5.1           3.5            1.4           0.2     0
1              4.9           3.0            1.4           0.2     0
2              4.7           3.2            1.3           0.2     0
3              4.6           3.1            1.5           0.2     0
4              5.0           3.6            1.4           0.2     0
..             ...           ...            ...           ...   ...
145            6.7           3.0            5.2           2.3     2
146            6.3           2.5            5.0           1.9     2
147            6.5           3.0            5.2           2.0     2
148            6.2           3.4            5.4           2.3     2
149            5.9           3.0            5.1           1.8     2

[150 rows x 5 columns]

In [364]:
# for i in df.iloc[:, 0:4]:
#     print(i)
sum_list = []
for i in range(150):
    sum_all = np.sum(df.iloc[i, 0:4])
    sum_list.append(sum_all)

In [365]:
df['sum'] = sum_list

In [366]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  type   sum
0              5.1           3.5            1.4           0.2     0  10.2
1              4.9           3.0            1.4           0.2     0   9.5
2              4.7           3.2            1.3           0.2     0   9.4
3              4.6           3.1            1.5           0.2     0   9.4
4              5.0           3.6            1.4           0.2     0  10.2
..             ...           ...            ...           ...   ...   ...
145            6.7           3.0            5.2           2.3     2  17.2
146            6.3           2.5            5.0           1.9     2  15.7
147            6.5           3.0            5.2           2.0     2  16.7
148            6.2           3.4            5.4           2.3     2  17.3
149            5.9           3.0            5.1           1.8     2  15.8

[150 rows x 6 columns]

In [42]:
np.mean(df.iloc[101:151, 5])

17.120408163265306

In [7]:
np.shape(df.iloc[:, 0:5])

(150, 5)

In [ ]:
def first_split(dataset):
    num_samples, num_features = np.shape(dataset)
    first_split_dict = {}
    for feature_index in range(num_features-1):
        value = dataset.iloc[:, feature_index]
        for threshold in np.unique(value):
            dataset_left = np.array([row for row in value if row <= threshold])
            dataset_right = np.array([row for row in value if row > threshold])
            parent = np.concatenate((dataset_left,dataset_right), axis=0)
            if len(dataset_left) > 0 and len(dataset_right) > 0:
                y, y_left, y_right = parent, dataset_left, dataset_right
                # info_gain[threshold] = information_gain(y, y_left, y_right)
                first_split_dict[threshold] = (y, y_left, y_right)
    return first_split_dict


def split(dataset):
    split_dict = {}
    for threshold in np.unique(dataset):
        dataset_left = np.array([row for row in value if row <= threshold])
        dataset_right = np.array([row for row in value if row > threshold])
        parent = np.concatenate((dataset_left,dataset_right), axis=0)
        if len(dataset_left) > 0 and len(dataset_right) > 0:
            y, y_left, y_right = parent, dataset_left, dataset_right
            # info_gain[threshold] = information_gain(y, y_left, y_right)
            split_dict[threshold] = (y, y_left, y_right)
    return split_dict


def best_threshold(dictionary):
    info = {}
    for i in dictionary.keys():
        for j in range(3):
            each_info = information_gain(dictionary[i][0], dictionary[i][1], dictionary[i][2])
            info[i] = each_info
    max_key = max(info, key=info.get)

    return max_key


def best_split(dataset, threshold):
    num_samples, num_features = np.shape(dataset)

    for feature_index in range(num_features-1):
        value = dataset.iloc[:, feature_index]

        dataset_left = np.array([row for row in value if row <= threshold])
        dataset_right = np.array([row for row in value if row > threshold])

    return dataset_left, dataset_right

In [ ]:
class Node():
    def __init__(self, feature_index, threshold, left_node, right_node, information_gain, value):
        self.feature_index = feature_index
        self.threshold = threshold
        self.left_node = left_node
        self.right_node = right_node
        self.information_gain = information_gain
        self.value = value


class DecisionTreeClassifier():
    def __init__(self, min_sample_split, max_depth):
        self.root = None

        self.min_sample_split = min_sample_split
        self.max_depth = max_depth


    def gini(self, thing):
        labels = np.unique(thing)
        gini = 0
        for i in labels:
            p = len(thing[thing == i]) / len(thing)
            gini += 1 - p**2

        return gini

    def information_gain(self, parent, left_child, right_child):
        l_weight = len(left_child) / len(parent)
        r_weight = len(right_child) / len(parent)
        information_gain = gini(parent) - (l_weight * gini(left_child) + r_weight * gini(right_child))
        return information_gain


    def split(self, dataset, threshold, feature_index):
        for i in dataset

    def best_split():





    def build_tree(self, X, y, current_depth = 0):
        num_samples = np.shape(X)
        num_features = np.shape(X)
        


    def print_tree():


    def fit():


    def predict():

In [ ]:
def gini_index(groups, classes):
	# count all samples at split point
	n_instances = float(sum([len(group) for group in groups]))
	# sum weighted Gini index for each group
	gini = 0.0
	for group in groups:
		size = float(len(group))
		# avoid divide by zero
		if size == 0:
			continue
		score = 0.0
		# score the group based on the score for each class
		for class_val in classes:
			p = [row[-1] for row in group].count(class_val) / size
			score += p * p
		# weight the group score by its relative size
		gini += (1.0 - score) * (size / n_instances)
	return gini

In [97]:
# Gini Index with Help

def gini_index(self, target):
    feature_labels = np.unique(target)
    g = 0
    for i in feature_labels:
        probability = len(target[target == i]) / len(target)
        g += probability**2
    return 1 - g

In [ ]:
# First split with help

def first_split(self, dataset, threshold):
    for value in dataset:
        if value[feature_index] <= threshold:
            left_data = value
        else:
            right_data = value
    return left_data, right_data

In [44]:
y = df.type

In [67]:
g = 0
features = np.unique(y)
for i in features:
    p = len(y[y == i])/len(y)
    print(p)
    g += p**2

print(1 - g)

0.3333333333333333
0.3333333333333333
0.3333333333333333
0.6666666666666667


In [9]:
def gini_index(target):
    feature_labels = np.unique(target)
    g = 0
    for i in feature_labels:
        probability = len(target[target == i]) / len(target)
        g += probability**2
    return 1 - g

def information_gain(parent, left_child, right_child):
    wl = len(left_child) / len(parent)
    wr = len(right_child) / len(parent)
    info_gain = gini_index(parent) - (wl * gini_index(left_child) + wr * gini_index(right_child))
    return info_gain

In [88]:
def first_split(dataset):
    num_samples, num_features = np.shape(dataset)
    first_split_dict = {}
    for feature_index in range(num_features-1):
        value = dataset.iloc[:, feature_index]
        for threshold in np.unique(value):
            dataset_left = np.array([row for row in value if row <= threshold])
            dataset_right = np.array([row for row in value if row > threshold])
            parent = np.concatenate((dataset_left,dataset_right), axis=0)
            if len(dataset_left) > 0 and len(dataset_right) > 0:
                y, y_left, y_right = parent, dataset_left, dataset_right
                # info_gain[threshold] = information_gain(y, y_left, y_right)
                first_split_dict[threshold] = (y, y_left, y_right)
    return first_split_dict


def split(dataset):
    split_dict = {}
    for threshold in np.unique(dataset):
        dataset_left = np.array([row for row in value if row <= threshold])
        dataset_right = np.array([row for row in value if row > threshold])
        parent = np.concatenate((dataset_left,dataset_right), axis=0)
        if len(dataset_left) > 0 and len(dataset_right) > 0:
            y, y_left, y_right = parent, dataset_left, dataset_right
            # info_gain[threshold] = information_gain(y, y_left, y_right)
            split_dict[threshold] = (y, y_left, y_right)
    return split_dict


def best_threshold(dictionary):
    info = {}
    for i in dictionary.keys():
        for j in range(3):
            each_info = information_gain(dictionary[i][0], dictionary[i][1], dictionary[i][2])
            info[i] = each_info
    max_key = max(info, key=info.get)

    return max_key


def best_split(dataset, threshold):
    num_samples, num_features = np.shape(dataset)
    best_split_dict = {}
    for feature_index in range(num_features-1):
        value = dataset.iloc[:, feature_index]

        dataset_left = np.array([row for row in value if row <= threshold])
        dataset_right = np.array([row for row in value if row > threshold])
        best_split_dict[feature_index] = (dataset_left, dataset_right)
    return best_split_dict

In [375]:
def First_Tree(dataset):
    split_1 = first_split(dataset)
    thresh_1 = best_threshold(split_1)
    best_split_1 = best_split(dataset, thresh_1)
    
    return best_split_1

In [171]:
First_Tree(df)

(array([0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1, 0.1, 0.2,
        0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2, 0.1, 0.2, 0.2,
        0.1, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]),
 array([0.4, 0.3, 0.4, 0.4, 0.3, 0.3, 0.3, 0.4, 0.5, 0.4, 0.4, 0.3, 0.3,
        0.6, 0.4, 0.3, 1.4, 1.5, 1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4,
        1. , 1.5, 1. , 1.4, 1.3, 1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5,
        1.2, 1.3, 1.4, 1.4, 1.7, 1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6,
        1.5, 1.3, 1.3, 1.3, 1.2, 1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1,
        1.3, 2.5, 1.9, 2.1, 1.8, 2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9,
        2.1, 2. , 2.4, 2.3, 1.8, 2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1,
        1.8, 1.8, 1.8, 2.1, 1.6, 1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8,
        1.8, 2.1, 2.4, 2.3, 1.9, 2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8]))

In [30]:
dict_1 = first_split(df)
thresh_1 = best_threshold(dict_1)
best_split_1 = best_split(df, thresh_1)

# best_split_1[3][1]

# dict_1

# thresh_1

array([0.4, 0.3, 0.4, 0.4, 0.3, 0.3, 0.3, 0.4, 0.5, 0.4, 0.4, 0.3, 0.3,
       0.6, 0.4, 0.3, 1.4, 1.5, 1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4,
       1. , 1.5, 1. , 1.4, 1.3, 1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5,
       1.2, 1.3, 1.4, 1.4, 1.7, 1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6,
       1.5, 1.3, 1.3, 1.3, 1.2, 1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1,
       1.3, 2.5, 1.9, 2.1, 1.8, 2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9,
       2.1, 2. , 2.4, 2.3, 1.8, 2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1,
       1.8, 1.8, 1.8, 2.1, 1.6, 1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8,
       1.8, 2.1, 2.4, 2.3, 1.9, 2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8])

In [92]:
def create_dataframes(dataset, bestSplit):
    col_names = []
    for i in dataset:
        col_names.append(i)


    for j in range(len(bestSplit)):
        leftList = [bestSplit[j][0][i] for i in range(len(bestSplit[j][0]))]
        rightList = [bestSplit[j][1][i] for i in range(len(bestSplit[j][1]))]

    if len(leftList) == len(dataset) or len(rightList) == len(dataset):
        
        return dataset

    else:
        dataset_left = dataset.loc[dataset[col_names[j]].isin(leftList)]
        dataset_right = dataset.loc[dataset[col_names[j]].isin(rightList)]

    return dataset_left, dataset_right


In [53]:
create_dataframes(df, best_split_1)[1]

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  type
5              5.4           3.9            1.7           0.4     0
6              4.6           3.4            1.4           0.3     0
15             5.7           4.4            1.5           0.4     0
16             5.4           3.9            1.3           0.4     0
17             5.1           3.5            1.4           0.3     0
..             ...           ...            ...           ...   ...
145            6.7           3.0            5.2           2.3     2
146            6.3           2.5            5.0           1.9     2
147            6.5           3.0            5.2           2.0     2
148            6.2           3.4            5.4           2.3     2
149            5.9           3.0            5.1           1.8     2

[116 rows x 5 columns]

In [99]:
dict_1 = first_split(df)
thresh_1 = best_threshold(dict_1)
best_split_1 = best_split(df, thresh_1)
left_dataset = create_dataframes(df, best_split_1)[0]
right_dataset = create_dataframes(df, best_split_1)[1]
dict_2 = first_split(left_dataset)
dict_3 = first_split(right_dataset)
thresh_2 = best_threshold(dict_2)
thresh_3 = best_threshold(dict_3)
best_split_2 = best_split(left_dataset,thresh_2)
best_split_3 = best_split(right_dataset, thresh_3)

# df3 = create_dataframes(right_dataset, best_split_3)
# df3
# thresh_3

best_split_3[1][0]

array([2.3, 2.3, 2.8, 2.8, 2.4, 2.9, 2.7, 2. , 2.2, 2.9, 2.9, 2.7, 2.2,
       2.5, 2.8, 2.5, 2.8, 2.9, 2.8, 2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 2.3,
       2.5, 2.6, 2.6, 2.3, 2.7, 2.9, 2.9, 2.5, 2.8, 2.7, 2.9, 2.5, 2.9,
       2.5, 2.7, 2.5, 2.8, 2.6, 2.2, 2.8, 2.8, 2.7, 2.8, 2.8, 2.8, 2.8,
       2.8, 2.6, 2.7, 2.5])

In [385]:
dict_3 = first_split(df3)
thresh_3 = best_threshold(dict_3)
best_split_3 = best_split(df3, thresh_3)
# thresh_3
best_split_3

{3: (array([0.4, 0.3, 0.4, 0.4, 0.3, 0.3, 0.3, 0.4, 0.5, 0.4, 0.4, 0.3, 0.3,
         0.6, 0.4, 0.3, 1.4, 1.5, 1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4,
         1. , 1.5, 1. , 1.4, 1.3, 1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5,
         1.2, 1.3, 1.4, 1.4, 1.7, 1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6,
         1.5, 1.3, 1.3, 1.3, 1.2, 1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1,
         1.3, 2.5, 1.9, 2.1, 1.8, 2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9,
         2.1, 2. , 2.4, 2.3, 1.8, 2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1,
         1.8, 1.8, 1.8, 2.1, 1.6, 1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8,
         1.8, 2.1, 2.4, 2.3, 1.9, 2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8]),
  array([], dtype=float64))}

In [342]:
gini_index(df2)

-37.0

In [160]:
gini_index(best_split_1[0])

0.2906574394463668

In [299]:
left = list(best_split_1[0])
np.shape(left)

(34,)

In [300]:
left = np.reshape(left, (len(left), 1))

In [301]:
left.shape

(34, 1)

In [302]:
dict_2 = split(left)
dict_2

{0.1: (array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3,
         0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2,
         0.5, 0.2, 0.2, 0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.2, 0.2, 0.2, 0.2,
         0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
         1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
         1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
         1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
         1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3, 2.5, 1.9, 2.1, 1.8,
         2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
         2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
         1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
         2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8]),
  array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1]),
  array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 0.2, 0.4,
         0.4, 0.3, 0